pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_guider_path: "./pretrained_weights/pose_guider.pth"
motion_module_path: "./pretrained_weights/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/experiment/experiment_ref_images_v1/art_monna_lisa.jpg": 
    - "./configs/inference/experiment/experiment_dwpose_v2/half_star_boy_pose1.mp4"
  "./configs/inference/experiment/experiment_ref_images_v1/full_viktor.jpg": 
    - "./configs/inference/experiment/experiment_dwpose_v2/full_1999_pose1.mp4"
